# Generated by Django 2.0.3 on 2018-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='votes',
            new_name='complexity_score',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='importance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='complexity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='importance_score',
            field=models.IntegerField(default=0),
        ),
    ]
