# Generated by Django 2.0.3 on 2018-10-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='description',
            new_name='tags',
        ),
    ]
