# Generated by Django 2.0.3 on 2018-10-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181028_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='description',
        ),
    ]
