# Generated by Django 2.0.3 on 2018-10-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181028_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='description',
            new_name='Tag_description',
        ),
    ]
